version: '3'
services:
  frontend:
    build: ./build/frontend
    volumes:
      - ./frontend/src:/frontend
    expose:
      - "3000"
  backend:
    build: ./build/backend
    volumes:
      - ./backend/src:/backend
    expose:
      - "8443"
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs
  nginx:
    build: ./build/reverseProxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build/reverseProxy:/etc/nginx
    depends_on:
      - frontend
      - backend
  oauth:
    build: ./build/oauth
    volumes:
      - ./oauth/src:/oauth
    expose:
      - "8080"